Added docker build checker

diff --git a/.ci/matrix_job_release.yaml b/.ci/matrix_job_release.yaml
--- a/.ci/matrix_job_release.yaml
+++ b/.ci/matrix_job_release.yaml
@@ -27,6 +27,11 @@ steps:
       mkdir -p /auto/mswg/release/ufm/plugins/${Plugin_name}
       cd plugins/${Plugin_name}/build
       bash -x ./docker_build.sh ${PLUGIN_VERSION} /auto/mswg/release/ufm/plugins/${Plugin_name} 
+      if [ $? -ne 0 ]; then
+        echo -e "docker_build - ${PLUGIN_NAME}/${PLUGIN_VERSION} failed"
+      else
+        echo -e "docker_build - ${PLUGIN_NAME}/${PLUGIN_VERSION} succeeded"
+      fi
       ls /auto/mswg/release/ufm/plugins/${Plugin_name}
 
     parallel: false
