Fixes

diff --git a/.github/workflows/pdr_plugin_ci_workflow.yml b/.github/workflows/pdr_plugin_ci_workflow.yml
--- a/.github/workflows/pdr_plugin_ci_workflow.yml
+++ b/.github/workflows/pdr_plugin_ci_workflow.yml
@@ -43,7 +43,12 @@ jobs:
         pytest -s $PDRPATH/tests/exclude_list_rest_api_tests.py --cov=$PDRPATH
         echo "Terminating standalone PDR process"
         sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
-
+        sleep 10
+        if pgrep -x "my_file.py" > /dev/null; then
+            echo "Failed to kill the process"
+            exit 1
+        fi
+        
     - name: Run full simulation test
       timeout-minutes: 10
       run: |
@@ -52,3 +57,9 @@ jobs:
         python $PDRPATH/tests/simulation_telemetry.py
         echo "Terminating standalone PDR process"
         sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
+        sleep 10
+        if pgrep -x "my_file.py" > /dev/null; then
+            echo "Failed to kill the process"
+            exit 1
+        fi
+        
