Fixes

diff --git a/.github/workflows/pdr_plugin_ci_workflow.yml b/.github/workflows/pdr_plugin_ci_workflow.yml
--- a/.github/workflows/pdr_plugin_ci_workflow.yml
+++ b/.github/workflows/pdr_plugin_ci_workflow.yml
@@ -42,12 +42,13 @@ jobs:
         sleep 10
         pytest -s $PDRPATH/tests/exclude_list_rest_api_tests.py --cov=$PDRPATH
         echo "Terminating standalone PDR process"
-        sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
-        sleep 10
-        if pgrep -x isolation_algo.py> /dev/null; then
-            echo "Failed to kill the process"
-            exit 1
-        fi
+        ps -ef | grep isolation_algo.py | grep -v grep | awk '{print $2}' | xargs kill -9 $1 >/dev/null 2>/dev/null
+        #sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
+        #sleep 10
+        #if pgrep -x isolation_algo.py> /dev/null; then
+        #    echo "Failed to kill the process"
+        #    exit 1
+        #fi
         
     - name: Run full simulation test
       timeout-minutes: 10
@@ -56,10 +57,11 @@ jobs:
         echo "Starting simulated test"
         python $PDRPATH/tests/simulation_telemetry.py
         echo "Terminating standalone PDR process"
-        sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
-        sleep 10
-        if pgrep -x isolation_algo.py> /dev/null; then
-            echo "Failed to kill the process"
-            exit 1
-        fi
+        ps -ef | grep isolation_algo.py | grep -v grep | awk '{print $2}' | xargs kill -9 $1 >/dev/null 2>/dev/null
+        #sudo pkill -0 isolation_algo.py && pkill -9 -f isolation_algo.py 2>/dev/null
+        #sleep 10
+        #if pgrep -x isolation_algo.py> /dev/null; then
+        #    echo "Failed to kill the process"
+        #    exit 1
+        #fi
         
